env:
  browser: true
  es6: true
extends:
  - standard
  - plugin:import/errors
  - plugin:import/warnings
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
settings:
  import/resolver: webpack
rules:
  no-multiple-empty-lines: 0
